print "10 >= 5 : " ++ 10 >= 5 ;
print "5  >= 5 : " ++ 5  >= 5 ;
print "17 >= 80: " ++ 17 >= 80;
print "55 >  5 : " ++ 55 >  5 ;
print "5  >  55: " ++ 5  >  55;
print "5  >  5 : " ++ 5  >  5 ;
print "========";
print "10 <= 5 : " ++ 10 <= 5 ;
print "5  <= 5 : " ++ 5  <= 5 ;
print "17 <= 80: " ++ 17 <= 80;
print "55 <  5 : " ++ 55 <  5 ;
print "5  <  55: " ++ 5  <  55;
print "5  <  5 : " ++ 5  <  5 ;
print "========";
print "10 == 10: " ++ 10 == 10;
print "10 != 5 : " ++ 10 != 5 ;
print "99 == 1 : " ++ 99 == 1 ;
print "81 != 81: " ++ 81 != 81;
print "========";
print "`era`    >= `happy` : " ++ "era"    >= "happy" ;
print "`steady` >= `change`: " ++ "steady" >= "change";
print "`thing`  >= `thing` : " ++ "thing"  >= "thing" ;
print "`shadow` >  `book`  : " ++ "shadow" >  "book"  ;
print "`teach`  >  `trade` : " ++ "teach"  >  "trade" ;
print "`wagon`  >  `wagon` : " ++ "wagon"  >  "wagon" ;
print "========";
print "`era`    <= `happy` : " ++ "era"    <= "happy" ;
print "`steady` <= `change`: " ++ "steady" <= "change";
print "`thing`  <= `thing` : " ++ "thing"  <= "thing" ;
print "`shadow` <  `book`  : " ++ "shadow" <  "book"  ;
print "`teach`  <  `trade` : " ++ "teach"  <  "trade" ;
print "`wagon`  <  `wagon` : " ++ "wagon"  <  "wagon" ;
print "========";
print "`wings` == `bubble` : " ++ "wings" == "bubble" ;
print "`parasite` != `joke`: " ++ "parasite" != "joke";
print "`monument` == `monument`: " ++ "monument" == "monument";
print "`edition`  != `edition` : " ++ "edition"  != "edition" ;
print "========";
print "true == false: " ++ true == false;
print "false == true: " ++ false == true;
print "true != false: " ++ true != false;
print "false != true: " ++ false != true;
print "3 and 4    : " ++ 3 and 4;
print "false and 4: " ++ false and 4;
print "3 or 4     : " ++ 3 or 4;
print "false or 4 : " ++ false or 4;
print "2 and 4 or false and 3: " ++ 2 and 4 or false and 3;
print "2 or 4 and false or 3 : " ++ 2 or 4 and false or 3 ;
